### ISSUE TITLE
Error in wacz import

### ISSUE THREAD

**Issue by despens** [emmadickson/unwarcit#3]
Installing unwarcit via git checkout and setup.py + installing wacz via pip (resulting in version 0.4.0 being installed), unwarcit produces the following error and is not able to run:

```py
# unwarcit --help
Traceback (most recent call last):
  File "/usr/local/bin/unwarcit", line 11, in <module>
    load_entry_point('unwarcit==0.0.0', 'console_scripts', 'unwarcit')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/unwarcit-0.0.0-py3.8.egg/unwarcit/main.py", line 1, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/unwarcit-0.0.0-py3.8.egg/unwarcit/unwarcit.py", line 3, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/dist-packages/unwarcit-0.0.0-py3.8.egg/unwarcit/util.py", line 2, in <module>
ImportError: cannot import name 'support_hash_file' from 'wacz.util' (/usr/local/lib/python3.8/dist-packages/wacz/util.py)
```

Does it maybe expect another version of wacz?

**Comment by ikreymer** [comment]
Sorry, this was related to a change in 0.4.0 release of wacz has an incompatible change that renames the function `support_hash_file`.
An easy fix is to rename it, or pin to the older version.
